spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/WaselPalestine
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  open-in-view: false
server:
  port: 8081

weather:
  api:
    key: 75a837afaa2618e2c287649a5553ba7d
    url: https://api.openweathermap.org/data/2.5/weather